# Generated by Django 4.2.9 on 2024-02-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managebudget', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
